--- 
clone: 
  depth: 1
kind: pipeline
name: GengKapak
steps: 
  - 
    commands: 
      - "bash ./run.sh"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
      GITHUB_TOKEN:
        from_secret: GH_TOKEN
    image: gengkapak/builder:latest
    name: Build Kernel
    trigger: 
      branch: 
        - main
